apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
spec:
  # https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#ttl-mechanism-for-finished-jobs
  # pods will be kept around for a day
  ttlSecondsAfterFinished: 86400
  backoffLimit: 0
  parallelism: {{ parallelism }}
  completions: {{ num_jobs }}
  template:
    spec:
      containers:
      - name: {{ name }}
        image: wwhuang/jhub-gofer:latest
        command: [
          "python", "worker.py", 
          "--api-url", "{{ api_addr }}"]
      restartPolicy: Never
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2G"
        limits:
          memory: "4G"
